services:
  postgres:
    image: postgres:18
    container_name: zappy_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: zappyuser
      POSTGRES_PASSWORD: zappypass
      POSTGRES_DB: zappydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
